# Generated by Django 2.2 on 2023-07-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, max_length=250, null=True, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=250, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Телефон')),
                ('function', models.CharField(blank=True, max_length=250, null=True, verbose_name='Должность')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный (is_active)')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Администратор (is_admin)')),
                ('is_staff', models.BooleanField(default=False, verbose_name='(is_staff)')),
                ('is_user', models.BooleanField(default=True, verbose_name='Обычный пользователь (is_user)')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['lastname', 'username', 'patronymic'],
            },
        ),
    ]
