# Generated by Django 2.2 on 2023-07-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_auto_20230713_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['id'], 'verbose_name': 'Доска', 'verbose_name_plural': 'Доски'},
        ),
    ]
