# Generated by Django 2.2 on 2023-07-13 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_auto_20230713_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='kanban.Board', verbose_name='Доска')),
            ],
            options={
                'verbose_name': 'Столбец',
                'verbose_name_plural': 'Столбцы',
                'ordering': ['board', 'position'],
            },
        ),
    ]
