# Generated by Django 2.2 on 2023-07-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0009_auto_20230717_1337'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='column',
            unique_together={('board', 'position')},
        ),
    ]
